---
- hosts: localhost
  gather_facts: false
  vars_files:
    - "roles/local-task/defaults/main.yml"
  roles:
    - { role: local-task }
  tasks:
    - debug: msg="Document Description [https://github.com/slzcc/crane/blob/master/docs/ETCD_NEW_CLUSTER.md]"
    - name: Check Node Add instance
      assert:
        that:
          - "k8s_cluster_add_node_ip_str not in kube_node_ip_str"
        fail_msg: "在 nodes 文件中的 kube-node 列表中存在 空值 或与 k8s-cluster-add-node 重复的 IP 会引起部署冲突, 请在 kube-node 移除后重试!"
        success_msg: "Check that the Nodes list is normal."

- name: Initialize Crane Env
  hosts: all
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
    crane_deploy_type: 'add_nodes'
    crane_tasks: 'k8s-add-nodes'
  vars_files:
    - "roles/cri-install/vars/containerd.yaml"
    - "roles/cri-install/vars/crio.yaml"
    - "roles/cri-install/vars/docker.yaml"
    - "roles/crane/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
    - "roles/etcd-cluster-management/vars/main.yml"
    - "roles/etcd-cluster-management/defaults/main.yml"
    - "roles/downloads-ssh-key/defaults/main.yml"
  roles:
    - { role: crane, tags: [crane] }
    
- name: Initialize SSH Secret Key
  hosts: kube-master[0]
  gather_facts: false
  become: yes
  become_method: sudo
  vars_files:
    - "roles/crane/defaults/main.yml"
  roles:
    - { role: downloads-ssh-key, tags: [copy_ssh_private_key]}

- name: Nodes Initialize
  hosts: k8s-cluster-add-node
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/kubernetes-cluster-management/defaults/main.yml"
    - "roles/crane/defaults/main.yml"
    - "roles/system-initialize/defaults/main.yml"
    - "roles/cri-install/vars/docker.yaml"
    - "roles/cri-install/vars/containerd.yaml"
    - "roles/cri-install/vars/crio.yaml"
    - "roles/cri-install/vars/cri-tools.yaml"
    - "roles/cri-install/vars/runc.yaml"
    - "roles/etcd-cluster-management/vars/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
    - "roles/kubernetes-cluster-management/defaults/tls.yaml"
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/kubernetes-networks/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
  roles:
    - { role: remove-cluster, tags: [clean], when: is_initialize_clean}
    - { role: cri-install, tags: [cri]}
    - { role: system-initialize, tags: [system]}
    - { role: downloads-packages, tags: [packages]}
  tasks:
    - { include: 'roles/kubernetes-cluster-management/includes/initialize-kubelet.yaml' }

- name: Create Bootstrap Config Files to Nodes, Copy Cluster CA Files to Nodes.
  hosts: kube-master[0]
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/system-initialize/defaults/main.yml"
    - "roles/crane/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
    - "roles/kubernetes-cluster-management/vars/kubelet.yaml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
    - "roles/kubernetes-cluster-management/defaults/tls.yaml"
    - "roles/etcd-cluster-management/vars/main.yml"
    - "roles/cri-install/vars/kubelet.yaml"
    - "roles/cri-install/vars/crio.yaml"
    - "roles/cri-install/vars/containerd.yaml"
  tasks:
    - { include: 'roles/kubernetes-cluster-management/includes/create-bootstrap.yaml' }
    - { include: 'roles/kubernetes-cluster-management/includes/k8s-add-nodes.yaml' }

- name: Create Kubernetes Cluster Nodes Config
  hosts: k8s-cluster-add-node
  gather_facts: true
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/kubernetes-manifests/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/system-initialize/defaults/main.yml"
    - "roles/crane/defaults/main.yml"
    - "roles/kubernetes-cluster-management/vars/kubelet.yaml"
    - "roles/cri-install/vars/kubelet.yaml"
    - "roles/cri-install/vars/crio.yaml"
    - "roles/cri-install/vars/containerd.yaml"
  tasks:
    - { include: 'roles/kubernetes-cluster-management/includes/configuretion-kubelet.yaml' }
    - { include: 'roles/kubernetes-cluster-management/includes/start-kubelet.yaml' }
    
- name: Kubernetes Cluster Setup
  hosts: kube-master[0]
  gather_facts: true
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/crane/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
    - "roles/kubernetes-cluster-management/defaults/main.yml"
  tasks:
    - name: Check all Nodes
      shell: "sleep 10"
    - { include: 'roles/kubernetes-cluster-management/includes/k8s-add-nodes/k8s-set-labels.yaml' }

- name: Sync Crane Delploy Files to Instance
  hosts: kube-master[0]
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
    crane_deploy_type: 'add_nodes'
  vars_files:
    - "roles/crane/defaults/main.yml"
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
  tasks:
    - { include: 'roles/crane/includes/sync-crane.yaml' }

- hosts: localhost
  gather_facts: false
  tasks:
    - debug: msg="请在 nodes 文件中把 k8s-cluster-add-node 列表内容移动到 kube-node 保证后续可用性!"