---
- hosts: localhost
  gather_facts: false
  roles:
    - { role: local-task }
    
- hosts: all
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  tasks:
    - name: Check all Nodes
      ping: 

- hosts: k8s-cluster:etcd
  gather_facts: false
  become: yes
  become_method: sudo
  roles:
    - { role: downloads-ssh-key, tags: [copy_ssh_private_key]}

- name: Nodes Initialize
  hosts: k8s-cluster-add-master
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/kubernetes-default/defaults/main.yml"
  roles:
    - { role: clean-install, tags: [clean], when: is_initialize_clean}
    - { role: docker-install, tags: [docker]}
    - { role: system-initialize, tags: [system]}
    - { role: downloads-packages, tags: [packages]}
  tasks:
    - { include_tasks: 'roles/kubernetes-default/includes/main.yml' }

- name: Run Nodes
  hosts: k8s-cluster-add-master
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  roles:
    - { role: kubernetes-manifests, tags: [kubernetes-manifests]}

- name: Copy Cluster CA Files to Nodes.
  hosts: kube-master[0]
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/k8s-add-master/defaults/main.yml"
  tasks:
    - { include_tasks: roles/k8s-add-master/includes/main.yml }
    
- name: Add Nodes
  hosts: k8s-cluster-add-master
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/kubernetes-default/defaults/main.yml"
  roles:
    - { role: k8s-add-master, tags: [add-master]}
    - { role: kubernetes-master, tags: [kubelet-master]}

- name: Update Master Cluster HaProxy Config
  hosts: kube-master
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  tasks:
    - { include_tasks: roles/k8s-add-master/includes/update-haproxy.yml }