---
- hosts: localhost
  gather_facts: false
  roles:
    - { role: local-task }

- name: Initialize Crane Env
  hosts: all
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
    crane_deploy_type: 'k8s_certifcate_rotation'
    crane_tasks: 'kubernetes-ca-rotation'
  vars_files:
    - "roles/cri-install/vars/containerd.yaml"
    - "roles/cri-install/vars/crio.yaml"
    - "roles/cri-install/vars/docker.yaml"
    - "roles/crane/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
    - "roles/downloads-ssh-key/defaults/main.yml"
  roles:
    - { role: crane, tags: [crane] }
    
- hosts: all
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/crane/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
    - "roles/downloads-ssh-key/defaults/main.yml"
  tasks:
    - { include_tasks: 'roles/kubernetes-ca-rotation/includes/initialize.yaml' }

- hosts: k8s-cluster:etcd
  gather_facts: false
  become: yes
  become_method: sudo
  remote_user: "{{ ssh_connect_user }}"
  vars_files:
    - "roles/crane/defaults/main.yml"
  roles:
    - { role: downloads-ssh-key, tags: [copy_ssh_private_key]}

- name: Create New CA
  hosts: kube-master[0]
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/kubernetes-cluster-management/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/system-initialize/defaults/main.yml"
    - "roles/crane/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/tls.yaml"
    - "roles/kubernetes-manifests/defaults/main.yml"
  roles:
    - { role: kubernetes-ca-rotation, tags: [k8s-ca-rotation]}

- name: Create New CA
  hosts: kube-master
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
    - "roles/kubernetes-cluster-management/defaults/tls.yaml"
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/system-initialize/defaults/main.yml"
    - "roles/crane/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
  tasks:
    - { include_tasks: 'roles/kubernetes-master/includes/copy-kubelet-admin.yaml' }
    # - { include_tasks: 'roles/kubernetes-master/includes/create-kubelet-config.yaml' }
    - { include_tasks: 'roles/kubernetes-ca-rotation/includes/update-cluster-master.yml' }

- name: Create New Bootstrap Config Files to Nodes.
  hosts: kube-master[0]
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/kubernetes-bootstraps/defaults/main.yml"
    - "roles/kubernetes-ca-rotation/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/system-initialize/defaults/main.yml"
    - "roles/crane/defaults/main.yml"
    - "roles/cri-install/vars/kubelet.yaml"
    - "roles/kubernetes-cluster-management/vars/kubelet.yaml"
  tasks:
    - { include_tasks: 'roles/kubernetes-bootstraps/includes/create-bootstrap.yml' }
    - { include_tasks: 'roles/kubernetes-ca-rotation/includes/update-cluster-node-ca.yml' }

- name: Copy Kubelet CA for Nodes
  hosts: kube-node
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/crane/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
    - "roles/kubernetes-networks/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
  tasks:
    - { include_tasks: 'roles/kubernetes-ca-rotation/includes/update-cluster-node.yml' }

- name: Update Cluster Network
  hosts: kube-master[0]
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/crane/defaults/main.yml"
    - "roles/etcd-install/vars/main.yml"
    - "roles/kubernetes-networks/defaults/calico.yaml"
    - "roles/kubernetes-networks/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
  tasks:
    - { include_tasks: 'roles/kubernetes-ca-rotation/includes/update-cluster-network.yml' }

- name: Sync Crane Delploy Files to Instance
  hosts: kube-master[0]
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
    crane_deploy_type: 'k8s_certifcate_rotation'
  vars_files:
    - "roles/crane/defaults/main.yml"
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
  tasks:
    - { include_tasks: 'roles/crane/includes/sync-crane.yaml' }