---
- hosts: localhost
  gather_facts: false
  roles:
    - { role: local-task }

- hosts: kube-master[0]:etcd:etcd-cluster-del-node
  become: yes
  gather_facts: true
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  tasks:
    - name: Check all Nodes
      ping: 

- name: Initialize Crane Env
  hosts: all
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
    crane_deploy_type: 'remove_etcd_nodes'
    crane_tasks: 'remove-etcd-nodes'
  vars_files:
    - "roles/cri-install/vars/containerd.yaml"
    - "roles/cri-install/vars/crio.yaml"
    - "roles/cri-install/vars/docker.yaml"
    - "roles/crane/defaults/main.yml"
    - "roles/kubernetes-default/defaults/configure.yaml"
    - "roles/downloads-ssh-key/defaults/main.yml"
  roles:
    - { role: crane, tags: [crane] }

- hosts: kube-master
  gather_facts: false
  become: yes
  become_method: sudo
  vars_files:
    - "roles/crane/defaults/main.yml"
  roles:
    - { role: downloads-ssh-key, tags: [copy_ssh_private_key]}

- name: Delete Etcd Clster Nodes
  hosts: kube-master[0]
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/etcd-install/defaults/main.yml"
    - "roles/crane/defaults/main.yml"
    - "roles/etcd-install/vars/main.yml"
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
    - "roles/kubernetes-default/defaults/configure.yaml"
    - "roles/etcd-install/defaults/tls.yaml"
  roles:
    - { role: etcd-del-node, tags: [etcd-del-node]}

- name: Clean Etcd Nodes DataDir
  hosts: etcd-cluster-del-node
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/etcd-install/defaults/main.yml"
    - "roles/crane/defaults/main.yml"
    - "roles/etcd-install/vars/main.yml"
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
    - "roles/kubernetes-default/defaults/configure.yaml"
    - "roles/etcd-install/defaults/tls.yaml"
  tasks:
    - { include_tasks: 'roles/etcd-del-node/includes/clean-nodes.yml' }

- name: Set Kubernetes Cluster Etcd Config
  hosts: kube-master[0]
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/crane/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
    - "roles/kubernetes-default/defaults/configure.yaml"
    - "roles/etcd-install/vars/main.yml"
  tasks:
    - { include_tasks: 'roles/etcd-add-node/includes/update-k8s-manifests.yml' }

- name: Set K8s Cluster Calico Network Config
  hosts: kube-master[0]
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/crane/defaults/main.yml"
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
    - "roles/kubernetes-default/defaults/configure.yaml"
    - "roles/etcd-install/vars/main.yml"
    - "roles/kubernetes-networks/defaults/calico.yaml"
    - "roles/kubernetes-networks/defaults/main.yml"
  tasks:
    - { include_tasks: 'roles/etcd-add-node/includes/update-k8s-calico.yml' }

- name: Sync Crane Delploy Files to Instance
  hosts: kube-master[0]
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
    crane_deploy_type: 'remove_etcd_nodes'
  vars_files:
    - "roles/crane/defaults/main.yml"
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
    - "roles/kubernetes-default/defaults/configure.yaml"
  tasks:
    - { include_tasks: 'roles/crane/includes/sync-crane.yaml' }