---
- hosts: localhost
  gather_facts: false
  roles:
    - { role: local-task }

- hosts: kube-master[0]:k8s-cluster-del-node
  become: yes
  gather_facts: true
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  tasks:
    - name: Check all Nodes
      ping: 

- name: Initialize Crane Env
  hosts: all
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
    crane_deploy_type: 'remove_k8s_nodes'
    crane_tasks: 'remove-k8s-node'
  vars_files:
    - "roles/cri-install/vars/containerd.yaml"
    - "roles/cri-install/vars/crio.yaml"
    - "roles/cri-install/vars/docker.yaml"
    - "roles/crane/defaults/main.yml"
    - "roles/kubernetes-default/defaults/configure.yaml"
    - "roles/downloads-ssh-key/defaults/main.yml"
  roles:
    - { role: crane, tags: [crane] }
    
- hosts: kube-master
  gather_facts: false
  become: yes
  become_method: sudo
  vars_files:
    - "roles/crane/defaults/main.yml"
  roles:
    - { role: downloads-ssh-key, tags: [copy_ssh_private_key]}
    
- name: Delete Kubernetes Cluster Nodes
  hosts: kube-master[0]
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/crane/defaults/main.yml"
    - "roles/system-initialize/defaults/main.yml"
    - "roles/kubernetes-default/defaults/configure.yaml"
  roles:
    - { role: k8s-del-nodes, tags: [k8s-del-nodes]}

- name: Clean Kubernetes Nodes DataDir
  hosts: k8s-cluster-del-node
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/crane/defaults/main.yml"
    - "roles/system-initialize/defaults/main.yml"
    - "roles/kubernetes-networks/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
    - "roles/kubernetes-default/defaults/configure.yaml"
  roles:
    - { role: clean-install, tags: [clean]}

- name: Sync Crane Delploy Files to Instance
  hosts: kube-master[0]
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
    crane_deploy_type: 'remove_k8s_nodes'
  vars_files:
    - "roles/crane/defaults/main.yml"
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
    - "roles/kubernetes-default/defaults/configure.yaml"
  tasks:
    - { include_tasks: 'roles/crane/includes/sync-crane.yaml' }