---
- hosts: localhost
  gather_facts: false
  vars_files:
    - "roles/local-task/defaults/main.yml"
  roles:
    - { role: local-task }
  tasks:
    - debug: msg="Document Description [https://github.com/slzcc/crane/blob/master/docs/REMOVE_CLUSTER.md]"

- name: Initialize Crane Env
  hosts: all
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
    crane_deploy_type: 'remove_cluster'
    crane_tasks: 'remove-cluster'
  vars_files:
    - "roles/cri-install/vars/containerd.yaml"
    - "roles/cri-install/vars/crio.yaml"
    - "roles/cri-install/vars/docker.yaml"
    - "roles/crane/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
    - "roles/etcd-cluster-management/vars/main.yml"
    - "roles/etcd-cluster-management/defaults/main.yml"
    - "roles/downloads-ssh-key/defaults/main.yml"
  roles:
    - { role: crane, tags: [crane] }

- name: Backups Etcd..
  hosts: etcd[0]
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/crane/defaults/main.yml"
    - "roles/system-initialize/defaults/main.yml"
    - "roles/etcd-cluster-management/defaults/main.yml"
    - "roles/etcd-cluster-management/defaults/tls.yaml"
    - "roles/etcd-cluster-management/vars/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
  tasks:
    - { include: 'roles/etcd-cluster-management/includes/backups-etcd-data.yaml' }

- name: Clean Kubernetes Cluster
  hosts: all
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/crane/defaults/main.yml"
    - "roles/cri-install/vars/docker.yaml"
    - "roles/cri-install/vars/containerd.yaml"
    - "roles/cri-install/vars/crio.yaml"
    - "roles/cri-install/vars/cri-tools.yaml"
    - "roles/cri-install/vars/cri-docker.yaml"
    - "roles/cri-install/vars/kubelet.yaml"    
    - "roles/system-initialize/defaults/main.yml"
    - "roles/kubernetes-networks/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
    - "roles/etcd-cluster-management/vars/main.yml"
  roles:
    - { role: remove-cluster, tags: [remove-cluster]}

- name: Sync Crane Delploy Files to Instance
  hosts: kube-master[0]
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
    crane_deploy_type: 'remove_cluster'
  vars_files:
    - "roles/crane/defaults/main.yml"
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
  tasks:
    - { include: 'roles/crane/includes/sync-crane.yaml' }