---
- hosts: localhost
  gather_facts: false
  roles:
    - { role: local-task }

- name: Initialize Crane Env
  hosts: k8s-cluster:etcd
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
    crane_deploy_type: 'upgrade_version'
    crane_tasks: 'kubernetes-upgrade'
  vars_files:
    - "roles/cri-install/vars/containerd.yaml"
    - "roles/cri-install/vars/crio.yaml"
    - "roles/cri-install/vars/docker.yaml"
    - "roles/crane/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
    - "roles/downloads-ssh-key/defaults/main.yml"
  roles:
    - { role: crane, tags: [crane] }
  tasks:
    - { include: 'roles/kubernetes-upgrade/includes/initialize.yaml' }
    
- name: Initialize SSH Secret Key
  hosts: kube-master:etcd
  gather_facts: true
  become: yes
  become_method: sudo
  vars_files:
    - "roles/crane/defaults/main.yml"
  roles:
    - { role: downloads-ssh-key, tags: [copy_ssh_private_key]}

# - name: Stop Cluster Scheduling
#   hosts: kube-master[0]
#   become: yes
#   become_method: sudo
#   vars:
#     ansible_ssh_pipelining: true
#   vars_files:
#     - "roles/crane/defaults/main.yml"
#     - "roles/kubernetes-cluster-management/defaults/configure.yaml"
#     - "roles/downloads-ssh-key/defaults/main.yml"
#   tasks:
#     - { include: 'roles/kubernetes-upgrade/includes/nodes/node-no-schedule.yaml' }

- name: Update Node Cluster Version
  hosts: kube-master:kube-node
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/crane/defaults/main.yml"
    - "roles/cri-install/vars/main.yml"
    - "roles/cri-install/vars/containerd.yaml"
    - "roles/cri-install/vars/crio.yaml"
    - "roles/cri-install/vars/docker.yaml"
    - "roles/cri-install/vars/kubelet.yaml"
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/etcd-cluster-management/defaults/tls.yaml"
    - "roles/etcd-cluster-management/vars/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
    - "roles/kubernetes-cluster-management/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/tls.yaml"
    - "roles/kubernetes-cluster-management/vars/haproxy.yaml"
    - "roles/kubernetes-cluster-management/vars/kubelet.yaml"
    - "roles/kubernetes-manifests/defaults/main.yml"
    - "roles/kubernetes-networks/defaults/calico.yaml"
    - "roles/kubernetes-networks/defaults/keepalived.yaml"
    - "roles/kubernetes-networks/defaults/main.yml"
    - "roles/system-initialize/defaults/main.yml"
  roles:
    - { role: kubernetes-upgrade, tags: [k8s-upgrade]}

# - name: Update Kubernetes Cluster Networks
#   hosts: kube-master[0]
#   become: yes
#   become_method: sudo
#   vars:
#     ansible_ssh_pipelining: true
#   vars_files:
#     - "roles/crane/defaults/main.yml"
#     - "roles/downloads-ssh-key/defaults/main.yml"
#     - "roles/kubernetes-manifests/defaults/main.yml"
#     - "roles/kubernetes-cluster-management/defaults/configure.yaml"
#     - "roles/etcd-cluster-management/vars/main.yml"
#     - "roles/kubernetes-networks/defaults/calico.yaml"
#     - "roles/kubernetes-networks/defaults/main.yml"
#     - "roles/kubernetes-upgrade/defaults/main.yml"
#   tasks:
#     - { include: 'roles/kubernetes-upgrade/includes/update-k8s-networks.yaml' }

- name: Update Kubernetes Cluster Tools
  hosts: kube-master[0]
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/kubernetes-upgrade/defaults/main.yml"
    - "roles/crane/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
    - "roles/downloads-ssh-key/defaults/main.yml"
  tasks:
    - { include: 'roles/kubernetes-upgrade/includes/check-cluster.yaml' }

# - name: Turn on Cluster Scheduling
#   hosts: kube-master[0]
#   become: yes
#   become_method: sudo
#   vars:
#     ansible_ssh_pipelining: true
#   vars_files:
#     - "roles/crane/defaults/main.yml"
#     - "roles/kubernetes-cluster-management/defaults/configure.yaml"
#     - "roles/downloads-ssh-key/defaults/main.yml"
#   tasks:
#     - { include: 'roles/kubernetes-upgrade/includes/nodes/node-schedule.yaml' }

- name: Sync Crane Delploy Files to Instance
  hosts: kube-master[0]
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
    crane_deploy_type: 'upgrade_version'
  vars_files:
    - "roles/crane/defaults/main.yml"
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
  tasks:
    - { include: 'roles/crane/includes/sync-crane.yaml' }