---
# Clean Docker
- name: Clean Docker Containers.
  shell: "{{ kubernetes_ctl_path }}docker rm -f $({{ kubernetes_ctl_path }}docker ps -f 'name=k8s*' -aq)"
  ignore_errors: true

- name: Clean Containerd Shim Services
  include: "roles/remove-cluster/includes/containerd/shim.yaml"
  when: is_remove_all or is_remove_docker_ce

- name: Docker Turn off Start Up
  service: 
    name: "{{ item }}"
    enabled: no
  with_items:
    - "docker"
    - "docker.socket"
  ignore_errors: true
  when: is_remove_all or is_remove_docker_ce

# Clean Docker Image
- name: Clean Docker Image
  include: "roles/remove-cluster/includes/docker/image.yaml"
  when: is_remove_all or is_remove_k8s_images

- name: Stop Docker (If there is)
  service:
    name: "{{ item }}"
    state: stopped
  ignore_errors: true
  with_items:
    - "docker"
    - "docker.socket"
  when: is_remove_all or is_remove_docker_ce

- name: Umount Docker Drive
  shell: "for i in `cat /proc/mounts | grep '{{ docker_data_root }}' | awk '{print $2}'`;do umount -l $i; done"
  when: is_remove_all or is_remove_docker_ce
  ignore_errors: true

# Clean Docker Configs
- name: Clean Docker Configs
  include: "roles/remove-cluster/includes/docker/config.yaml"
  when: is_remove_all or is_remove_docker_ce
  
# Clean Docker Package
- name: Clean Docker Package
  include: "roles/remove-cluster/includes/docker/package.yaml"
  when: is_remove_all or is_remove_not_crane_docker_ce

# Clean Docker Binary
- name: Clean Docker Binary
  include: "roles/remove-cluster/includes/docker/binary.yaml"
  when: is_remove_all or is_remove_docker_ce

# Clean Docker Data
- name: Clean Docker Data
  include: "roles/remove-cluster/includes/docker/data.yaml"
  when: is_remove_all or (is_remove_docker_ce and is_remove_docker_dir)
  
# Clean Docker Socket
- name: Clean Docker Socket
  shell: "rm -rf {{ docker_socket_path }}"
  when: is_remove_all or is_remove_docker_ce
  ignore_errors: true

- name: Clean Docker Users
  include: "roles/remove-cluster/includes/docker/system.yaml"
  when: is_remove_all or is_remove_docker_ce