---
- name: Check CriDocker Dir
  shell: "ls {{ kubernetes_ctl_path }}cri-docker"
  register: CHECK_CIRDOCKER_BIN_PACKAGE
  ignore_errors: true

- name: Copy CriDocker Compressed File
  copy: 
    src: "roles/downloads-packages/files/cri-dockerd-{{ cri_docker_version }}.{{ os_arch }}.tar.gz"
    dest: "{{ temporary_dirs }}cri-dockerd-{{ cri_docker_version }}.{{ os_arch }}.tar.gz"
    mode: 0644
    owner: "{{ ssh_connect_user }}"
  when: CHECK_CIRDOCKER_BIN_PACKAGE is failed

- name: Unpack the CriDocker. Tar. Gz
  shell: "tar zxf {{ temporary_dirs }}cri-dockerd-{{ cri_docker_version }}.{{ os_arch }}.tar.gz -C {{ temporary_dirs }}"
  when: CHECK_CIRDOCKER_BIN_PACKAGE is failed

- name: Copy Binary file to the execution directory
  shell: "cp -a {{ temporary_dirs }}cri-docker/cri-docker {{ kubernetes_ctl_path }}"
  when: CHECK_CIRDOCKER_BIN_PACKAGE is failed

- name: Modifying file Permissions
  shell: "chmod +x {{ kubernetes_ctl_path }}cri-docker"
  when: CHECK_CIRDOCKER_BIN_PACKAGE is failed