---
# Clean Crane
- name: Clean Crane
  include: "roles/remove-cluster/includes/crane.yaml"

# Clean Etcd
- name: Clean Etcd
  include: "roles/remove-cluster/includes/etcd.yaml"
  when:
    - is_remove_etcd

# Clean Kubernetes
- name: Clean Kubernetes
  include: "roles/remove-cluster/includes/kubernetes.yaml"

# Clean CNI
- name: Clean CNI
  include: "roles/remove-cluster/includes/cni.yaml"
  
# Clean Haproxy
- name: Clean CNI
  include: "roles/remove-cluster/includes/haproxy.yaml"

# Clean IPVS and Iptables
- name: Clean Iptables
  include: "roles/remove-cluster/includes/iptables.yaml"

# Clean Docker
- name: Clean Docker
  include: "roles/remove-cluster/includes/docker/main.yaml"

# Clean CriDocker
- name: Clean Docker
  include: "roles/remove-cluster/includes/cri-docker.yaml"

# Clean Containerd
- name: Clean Containerd
  include: "roles/remove-cluster/includes/containerd/main.yaml"
  
# Clean CRIO
- name: Clean CRIO
  include: "roles/remove-cluster/includes/crio/main.yaml"

# Clean runC
- name: Clean runC
  include: "roles/remove-cluster/includes/runc.yaml"

# Clean Cri-Tools
- name: Clean Cri-Tools
  include: "roles/remove-cluster/includes/cri-tools.yaml"

# Clean General Network
- name: Clean General Network
  include: "roles/remove-cluster/includes/{{ item }}.yaml"
  with_items:
    - "cilium"
    - "calico"

# Clean Kernel
- name: Clean Kernel
  include: "roles/remove-cluster/includes/kernel.yaml"

# Clean Other
- name: Clean Other
  include: "roles/remove-cluster/includes/other.yaml"
  
# Reload Systemd
- name: Systemd Reload
  shell: "systemctl daemon-reload"