---
# Deploy
## ********************************************************************************************************************************
# Check kubernetes image
- name: Check kubernetes image
  shell: 'for i in {{ k8s_cluster_component_registry }}/kube-proxy:{{ k8s_version }} {{ k8s_cluster_component_registry }}/kube-apiserver-amd64:{{ k8s_version }} {{ k8s_cluster_component_registry }}/kube-controller-manager:{{ k8s_version }} {{ k8s_cluster_component_registry }}/kube-scheduler:{{ k8s_version }} haproxy calico/node:{{ calico_version }} calico/cni:{{ calico_version }} calico/kube-controllers:{{ calico_version }} coredns/coredns:{{ dns_version }} {{ k8s_cluster_component_registry }}/etcd:{{ etcd_version }} {{ k8s_cluster_component_registry }}/pause:{{ pause_version }} slzcc/keepalived; do if [ ! `{{ kubernetes_ctl_path }}docker images --filter=reference="$i*" -aq | wc -l` -ge 1 ] ;then echo 1 > /dev/stderr && exit 1 ; fi ; done'
  register: check_k8s_image
  ignore_errors: true

- name: Check Binary files
  shell: 'for i in cfssl cfssljson kubelet kubectl; do if [ "`ls {{ kubernetes_ctl_path }}$i | wc -l`" -eq 0 ] ; then echo 1 > /dev/stderr && exit 1; fi ; done'
  register: check_binary_files
  ignore_errors: true

- name: Check Kubectl Version
  shell: "{{ kubernetes_ctl_path }}kubectl version --short=true --client=true | awk '{print $3}'"
  register: check_kubectl_version
  ignore_errors: true

- name: Pull the Image
  shell: "{{ kubernetes_ctl_path }}docker rm -f import-kubernetes-temporary | true && {{ kubernetes_ctl_path }}docker run --name import-kubernetes-temporary -d -v /var/run/docker.sock:/var/run/docker.sock:ro {{ k8s_image_deploy_repo }}:{{ k8s_version }}.{{ build_k8s_version }} sleep 1234567"
  when: (check_kubectl_version.stdout != k8s_version) or (check_k8s_image is failed) or (check_binary_files is failed)
  
- name: Export the Image
  shell: 'until {{ kubernetes_ctl_path }}docker exec -i import-kubernetes-temporary bash /docker-image-import.sh ; do >&2 echo "Starting..." && sleep 1 ; done'
  when: check_k8s_image is failed

- name: Export the cfssl and cfssljson
  include: "roles/downloads-packages/includes/cfssl/docker/image_deploy.yaml" 
  when: check_binary_files is failed

- name: Export the Kubelet and kubectl
  include: "roles/downloads-packages/includes/kubernetes/docker/image_deploy.yaml" 
  when: check_kubectl_version.stdout != k8s_version

- name: Export the CNI
  include: "roles/downloads-packages/includes/cni/docker/image_deploy.yaml" 
  when: check_binary_files is failed

- name: Export the Cilium
  include: "roles/downloads-packages/includes/cilium/docker/image_deploy.yaml" 
  when: general_network_drive == "cilium"

- name: Clean Temporary Container
  shell: "{{ kubernetes_ctl_path }}docker rm -f import-kubernetes-temporary"
  ignore_errors: true