---
- name: Clean Calico directory.
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/var/lib/calico"
    - "/var/lib/cni/networks"
    - "/var/run/calico"
    - "/var/log/calico/cni"
  ignore_errors: true

- name: Clean Calico CNI.
  shell: "rm -rf {{ cni_config_dir }}/{{ item }}"
  with_items:
    - "10-calico.conflist*"
    - "calico-kubeconfig"
  ignore_errors: true

- name: Clean Calico IP Route
  shell: >
    ip route | grep 'cali' | awk '{print $1}' | xargs -i ip route delete {}
  ignore_errors: true

- name: Clean Calico IP Equipment
  shell: >
    ip neigh | grep 'cali' | awk '{print $3}' | xargs -i ip link delete {}
  ignore_errors: true