## Containerd
## ********************************************************************************************************************************

# https://github.com/containerd/containerd/releases
containerd_version: 1.6.23

# 自定义配置
is_containerd_config_custom: true

# 安装的介质(在线离线)可选 local_binary/http_binary
# 当选择 local_binary 时, 需要保证 files 拥有 cri type 的二进制包 
containerd_install_type: "{{ cri_drive_install_type }}"

# Containerd cgroup drive
containerd_cgroup_drive: '{{ cgroup_drive }}'

# Containerd 存储路径
containerd_data_root: '/var/lib/containerd'

# Containerd Plugin Path
# Containerd 存储路径
containerd_plugin_root: '/opt/containerd'

# Containerd Socket 文件路径
containerd_run_path: '/run/containerd'
containerd_socket_path: '{{ containerd_run_path }}/containerd.sock'

# 强制安装 containerd, 当可能存在不同版本 containerd 可以强制安装统一版本
is_mandatory_containerd_install: false