---
- name: Move CRIO binray to bin Path
  shell: "cp -a {{ temporary_dirs }}cri-o/bin/{{ item }} {{ kubernetes_ctl_path }}"
  with_items:
    - "conmon"
    - "crio"
    - "crio-status"
    - "crun"
    - "pinns"

- name: Copy crio Systemd Config
  template: 
    src: "roles/cri-install/templates/cri-o/{{ item }}"
    mode: 0644
    owner: "{{ ssh_connect_user }}"
    dest: "{{ systemd_default_dirs }}{{ item }}"
  with_items:
    - "crio.service"

- name: Copy crio Systemd Env Config
  template: 
    src: "roles/cri-install/templates/cri-o/{{ item }}"
    mode: 0644
    owner: "{{ ssh_connect_user }}"
    dest: "/etc/default/crio"
  with_items:
    - "crio.service.conf"

- name: Create crio Config Path
  file:
    path: "/etc/crio"
    mode: 0755
    owner: "{{ ssh_connect_user }}"
    state: directory

- name: Copy crio Config
  template: 
    src: "roles/cri-install/templates/cri-o/{{ item }}"
    mode: 0644
    owner: "{{ ssh_connect_user }}"
    dest: "/etc/crio/crio.conf"
  with_items:
    - "crio.conf"