---
- name: Deploy Jenkins Service *
  file:
    path: "{{ item }}"
    mode: 0755
    owner: "{{ ssh_connect_user }}"
    state: directory
  with_items:
  - "{{ temporary_dirs }}jenkins"
  ignore_errors: true

- name: Deploy Jenkins Service **
  template: 
    src: "roles/kubernetes-addons/templates/jenkins/{{ item }}"
    dest: "{{ temporary_dirs }}jenkins/{{ item }}"
    mode: 0644
    owner: "{{ ssh_connect_user }}" 
  with_items:
    - "1_jenkins.yaml"
    - "2_ingress.yaml"
    - "3_jenkins_svc.yaml"

- name: Deploy Jenkins Service ***
  shell: 'until {{ kubernetes_ctl_path }}kubectl apply -f {{ temporary_dirs }}jenkins/ ; do >&2 echo "Starting..." && sleep 1 ; done'