---
- name: Deploy CFSSL Binary Files
  include: "roles/downloads-packages/includes/cfssl/http_download.yaml"
  
- name: Deploy Kubernetes Binary Files
  include: "roles/downloads-packages/includes/kubernetes/http_download.yaml"

- name: Deploy CNI Binary Files
  include: "roles/downloads-packages/includes/cni/http_download.yaml"

- name: Deploy Cilium Binary Files
  include: "roles/downloads-packages/includes/cilium/http_download.yaml"
  when:
  - general_network_drive == 'cilium'
  - is_kube_master

- name: Set Path Permissions
  shell: "chmod 777 {{ kubernetes_cni_dirs }}"
  ignore_errors: true