---
# - name: Stop Kubelet
#   service: 
#     name: kubelet
#     state: stopped

- name: Copy kubelet.service Files
  template: 
    src: "roles/kubernetes-upgrade/templates/node/{{ k8s_upgrade_version }}/systemd/kubelet.service.j2"
    dest: "{{ systemd_default_dirs }}kubelet.service"
    mode: 0644
    owner: "{{ ssh_connect_user }}"

- name: Copy Kubelet Env Config
  template: 
    src: "roles/kubernetes-upgrade/templates/node/{{ k8s_upgrade_version }}/systemd/kubernetes-flags.j2"
    dest: "{{ kubelet_work_dirs }}kubernetes-flags.env"
    mode: 0644
    owner: "{{ ssh_connect_user }}"
  when: is_k8s_upgrade_calico_node_kubelet_env_config

- name: Copy 10-kubelet.conf Files
  template: 
    src: "roles/kubernetes-upgrade/templates/node/{{ k8s_upgrade_version }}/systemd/10-kubelet.j2"
    dest: "{{ systemd_etc_dirs }}kubelet.service.d/10-kubelet.conf"
    mode: 0644
    owner: "{{ ssh_connect_user }}"

- name: Copy Kubelet Config
  template: 
    src: "roles/kubernetes-upgrade/templates/node/{{ k8s_upgrade_version }}/kubelet/config.j2"
    dest: "{{ kubelet_work_dirs }}config.yaml"
    mode: 0644
    owner: "{{ ssh_connect_user }}"
    
- name: System Reload
  shell: "systemctl daemon-reload"

- name: Restart Kubelet
  service:
    name: kubelet
    state: restarted