- name: Create CriDocker Run Directory
  file:
    path: "{{ cri_docker_socket_home }}"
    mode: 0755
    owner: "{{ ssh_connect_user }}"
    state: directory

- name: Copy CriDocker Systemd Config
  template: 
    src: "roles/cri-install/templates/cri-docker/{{ item }}"
    mode: 0644
    owner: "{{ ssh_connect_user }}"
    dest: "{{ systemd_default_dirs }}{{ item }}"
  with_items:
    - "cri-docker.service"
    - "cri-docker.socket"

- name: CriDocker Systemd Reload Config Cache
  shell: "systemctl daemon-reload"