---
- name: Clean Docker..
  include: "roles/remove-cluster/includes/docker/main.yaml"
  when: clean_up_old_before_installing

- name: Close Kubelet..
  include: "roles/cri-install/includes/docker/kubernetes/close-kubelet.yaml"
  when: is_docker_install_close_kubelet

- name: Check Docker-ce Version
  shell: "docker -v | awk '{print $3}' | awk -F',' '{print $1}'"
  register: check_docker
  ignore_errors: true

- name: Initialize Docker-ce
  include: "roles/cri-install/includes/docker/initialize.yaml"
  ignore_errors: true

- name: Check Docker Bin, Ensure that the command line is available.
  include: 'roles/kubernetes-upgrade/includes/cri/docker.yaml'
  when: 
    - cri_k8s_default == 'docker'
    - check_docker.stderr == ''
  ignore_errors: true

- name: Install Docker-ce
  include: "roles/cri-install/includes/docker/os.yaml"
  when: is_mandatory_docker_install or check_docker.stderr
  ignore_errors: true
  
- name: Check DockerD Daemon.js isFile
  shell: "ls /etc/docker/daemon.json"
  register: check_daemon_file
  ignore_errors: true
  when: is_docker_daemon_config

- name: Check DockerD Daemon.js MD5 *
  shell: "md5sum /etc/docker/daemon.json | awk '{print $1}'"
  register: check_old_md5
  ignore_errors: true
  when: 
    - is_docker_daemon_config 
    - check_daemon_file.stderr != ''

- name: Check DockerD Daemon.js MD5 **
  template: 
    src: "roles/cri-install/templates/docker/daemon.j2"
    dest: "{{ temporary_dirs }}cri/.daemon.json"
    mode: 0644
    owner: "{{ ssh_connect_user }}"
  when: 
    - is_docker_daemon_config
    - check_daemon_file.stderr != ''

- name: Check DockerD Daemon.js MD5 **
  shell: "md5sum {{ temporary_dirs }}cri/.daemon.json | awk '{print $1}'"
  register: check_new_md5
  ignore_errors: true
  when: 
    - is_docker_daemon_config 
    - check_daemon_file.stderr != ''
    
- name: Stop DockerD
  service:
    name: ["docker", "containerd"]
    state: stopped
  when: 
    - is_docker_daemon_config 
    - (check_old_md5.stderr == '')
    - check_old_md5.stdout != check_new_md5.stdout
    - not is_kube_simple
  ignore_errors: true

- name: Create Docker Config DIR
  file:
    path: "/etc/docker"
    mode: 0755
    owner: "{{ ssh_connect_user }}"
    state: directory
  ignore_errors: true

- name: Copy Dockerd Daemon JSON Config
  template: 
    src: "roles/cri-install/templates/docker/daemon.j2"
    dest: "/etc/docker/daemon.json"
    mode: 0644
    owner: "{{ ssh_connect_user }}"
  when: 
    - is_mandatory_docker_config or is_docker_daemon_config and check_daemon_file.stderr != ''
  ignore_errors: true
  
- name: Docker-ce Powered UP And Startd
  service: 
    name: docker
    enabled: yes
  ignore_errors: true

- name: Start DockerD
  service:
    name: docker
    state: started
  ignore_errors: true
  when: not is_kube_simple

- name: Install CriDocker
  include: "roles/cri-install/includes/cri-docker/os.yaml"
  when: is_cir_docker_install

- name: Start CriDocker
  include: "roles/cri-install/includes/cri-docker/_system_start.yaml"
  when: is_cir_docker_install

- name: Open Kubelet..
  include: "roles/cri-install/includes/docker/kubernetes/open-kubelet.yaml"
  when: is_docker_install_close_kubelet
  ignore_errors: true