FROM linuxkit/kernel:4.9.184 AS ksrc
# https://github.com/linuxkit/linuxkit/blob/master/docs/kernels.md

FROM ubuntu:18.04

COPY --from=ksrc /kernel.tar /mnt
COPY --from=ksrc /kernel-dev.tar /mnt
COPY --from=ksrc /kernel-headers.tar /mnt

RUN tar xf /mnt/kernel-dev.tar -C / && \
    tar xf /mnt/kernel.tar -C / && \
    tar xf /mnt/kernel-headers.tar -C / && \
    rm -rf /mnt/*
    
RUN apt update && \
    echo "Asia/Shanghai" > /etc/timezone && \
    apt install -y tzdata && \
    dpkg-reconfigure -f noninteractive tzdata && \
    apt install -y git unzip vim python3 python3-pip curl wget lrzsz \
    dnsutils inetutils-ping ethtool telnet iproute2 iotop jq ctop \
    inetutils-traceroute traceroute tcpdump dbus inetutils-ping \
    net-tools openssh-server iptables ipset netcat-traditional \
    fonts-baekmuk fonts-nanum language-pack-zh-hans dstat sudo \
    kernel-common kernel-package kernel-patch-scripts kernel-wedge && \
    rm -rf  /var/cache/apt/archives/* && \
    apt clean

RUN service ssh start && \
    ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa && \
    cat ~/.ssh/id_rsa.pub > ~/.ssh/authorized_keys && \
    chmod 600 -R ~/.ssh/authorized_keys && \
    ssh-keyscan -t rsa 127.0.0.1 -p 22 > ~/.ssh/known_hosts && \
    ssh-keygen -H -f ~/.ssh/known_hosts

RUN update-rc.d ssh defaults 98 && \
    echo 'root:root' |chpasswd && \
    sed -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config

ENV TZ=Asia/Shanghai \
    LANG=zh_CN.utf8 

EXPOSE 22

CMD ["/sbin/init"]
