---
# Cilium
## ********************************************************************************************************************************
- name: Check Cilium Dir
  shell: "ls {{ kubernetes_ctl_path }}cilium"
  register: CHECK_CILIUM_BIN_PACKAGE
  ignore_errors: true

- name: Download Cilium Package
  shell: "wget -qO- 'https://github.com/slzcc/crane/releases/download/v1.25.0.0/cilium' > {{ kubernetes_ctl_path }}cilium"
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
  when: CHECK_CILIUM_BIN_PACKAGE is failed

- name: Modifying file Permissions
  shell: "chmod +x {{ kubernetes_ctl_path }}cilium"
  when: CHECK_CILIUM_BIN_PACKAGE is failed
