---
- name: Configure CNI to execute files in localhost
  include: "roles/downloads-packages/includes/cni/http_download.yaml"
  when: is_using_local_files_deploy

- name: Configure CNI to execute files in image deploy
  include: "roles/downloads-packages/includes/cni/docker/image_deploy.yaml"
  when: 
    - not is_using_local_files_deploy
    - cri_k8s_default == 'docker'

- name: Configure CNI to execute files in image deploy
  include: "roles/downloads-packages/includes/cni/containerd/image_deploy.yaml"
  when:
    - not is_using_local_files_deploy
    - cri_k8s_default == 'containerd'

- name: Set Path Permissions
  shell: "chmod 777 {{ kubernetes_cni_dirs }}"
  ignore_errors: true